# .streamlit/secrets.toml

[connections.snowflake]
account = "PSZKBQY-ZV52731"
user = "JOHNV54321"
password = "&JT#e:'238~NR._"
role = "sysadmin"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true

