# .streamlit/secrets.toml

[connections.snowflake]
account = "PSZKBQY-ZV52731"
user = "JOHNV54321"
password = "Jp%!Cuw)5fQ}CaX"
role = "sysadmin"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
